apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ljwx-dify-dev

resources:
  - ../../base

images:
  - name: ghcr.io/brunogaosz/ljwx-dify-api
    newName: ghcr.io/brunogaosz/ljwx-dify-api
    newTag: latest
  - name: ghcr.io/brunogaosz/ljwx-dify-web
    newName: ghcr.io/brunogaosz/ljwx-dify-web
    newTag: latest
  - name: qdrant/qdrant
    newTag: v1.12.6
