---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ljwx-health-device-approval-config
  namespace: ljwx-health
  labels:
    app: ljwx-boot
    component: device-approval
    helm.sh/chart: ljwx-health-0.1.0
    app.kubernetes.io/name: ljwx-health
    app.kubernetes.io/instance: ljwx-health
    app.kubernetes.io/version: 1.0.6
    app.kubernetes.io/managed-by: Helm
data:
  DEVICE_APPROVAL_AUTO_CLEANUP_DAYS: '30'
  DEVICE_APPROVAL_BATCH_SIZE_LIMIT: '100'
  DEVICE_APPROVAL_TIMEOUT_HOURS: '72'
  DEVICE_APPROVAL_EVENT_THREAD_POOL_SIZE: '10'
  DEVICE_APPROVAL_EVENT_QUEUE_CAPACITY: '100'
  DEVICE_APPROVAL_METRICS_ENABLED: 'true'
  DEVICE_APPROVAL_LOG_LEVEL: INFO
  DEVICE_APPROVAL_EVENT_LISTENER_LOG_LEVEL: INFO
  DEVICE_APPROVAL_METRICS_SERVICE_LOG_LEVEL: DEBUG
  DEVICE_APPROVAL_QUERY_CACHE_TTL: '300'
  DEVICE_APPROVAL_HISTORY_QUERY_OPTIMIZATION: 'true'
  application-device-approval.yml: "# Device V2.1 - \u8BBE\u5907\u7ED1\u5B9A\u5BA1\
    \u6279\u6A21\u5757\u4E13\u7528\u914D\u7F6E\n# \u81EA\u52A8\u52A0\u8F7D\u5F53 spring.profiles.include=device-approval\
    \ \u65F6\u751F\u6548\n\ndevice:\n  approval:\n    # \u5BA1\u6279\u6D41\u7A0B\u914D\
    \u7F6E\n    auto-cleanup-days: ${DEVICE_APPROVAL_AUTO_CLEANUP_DAYS:30}\n    batch-size-limit:\
    \ ${DEVICE_APPROVAL_BATCH_SIZE_LIMIT:100}\n    timeout-hours: ${DEVICE_APPROVAL_TIMEOUT_HOURS:72}\n\
    \n    # \u4E8B\u4EF6\u53D1\u5E03\u914D\u7F6E\n    events:\n      async-thread-pool-size:\
    \ ${DEVICE_APPROVAL_EVENT_THREAD_POOL_SIZE:10}\n      async-queue-capacity: ${DEVICE_APPROVAL_EVENT_QUEUE_CAPACITY:100}\n\
    \n    # \u53EF\u89C2\u6D4B\u6027\u914D\u7F6E\n    observability:\n      metrics-enabled:\
    \ ${DEVICE_APPROVAL_METRICS_ENABLED:true}\n      log-level: ${DEVICE_APPROVAL_LOG_LEVEL:INFO}\n\
    \      event-listener-log-level: ${DEVICE_APPROVAL_EVENT_LISTENER_LOG_LEVEL:INFO}\n\
    \      metrics-service-log-level: ${DEVICE_APPROVAL_METRICS_SERVICE_LOG_LEVEL:DEBUG}\n\
    \n    # \u6027\u80FD\u4F18\u5316\u914D\u7F6E\n    performance:\n      query-cache-ttl:\
    \ ${DEVICE_APPROVAL_QUERY_CACHE_TTL:300}\n      history-query-optimization: ${DEVICE_APPROVAL_HISTORY_QUERY_OPTIMIZATION:true}\n\
    \n# Logback \u65E5\u5FD7\u914D\u7F6E (\u8986\u76D6\u9ED8\u8BA4\u914D\u7F6E)\n\
    logging:\n  level:\n    com.ljwx.modules.health.service.DeviceBindApprovalServiceImpl:\
    \ ${DEVICE_APPROVAL_LOG_LEVEL:INFO}\n    com.ljwx.modules.health.listener.DeviceBindApprovalEventListener:\
    \ ${DEVICE_APPROVAL_EVENT_LISTENER_LOG_LEVEL:INFO}\n    com.ljwx.modules.health.service.DeviceBindApprovalMetricsService:\
    \ ${DEVICE_APPROVAL_METRICS_SERVICE_LOG_LEVEL:DEBUG}\n"
---
apiVersion: v1
kind: Service
metadata:
  name: ljwx-health-admin
  namespace: ljwx-health
  labels:
    app: ljwx-admin
    helm.sh/chart: ljwx-health-0.1.0
    app.kubernetes.io/name: ljwx-health
    app.kubernetes.io/instance: ljwx-health
    app.kubernetes.io/version: 1.0.6
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: ljwx-admin
---
apiVersion: v1
kind: Service
metadata:
  name: ljwx-health-bigscreen
  namespace: ljwx-health
  labels:
    app: ljwx-bigscreen
    helm.sh/chart: ljwx-health-0.1.0
    app.kubernetes.io/name: ljwx-health
    app.kubernetes.io/instance: ljwx-health
    app.kubernetes.io/version: 1.0.6
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
  - port: 5225
    targetPort: 5225
    protocol: TCP
    name: http
  selector:
    app: ljwx-bigscreen
---
apiVersion: v1
kind: Service
metadata:
  name: ljwx-health-boot
  namespace: ljwx-health
  labels:
    app: ljwx-boot
    helm.sh/chart: ljwx-health-0.1.0
    app.kubernetes.io/name: ljwx-health
    app.kubernetes.io/instance: ljwx-health
    app.kubernetes.io/version: 1.0.6
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
  - port: 9998
    targetPort: 9998
    protocol: TCP
    name: http
  selector:
    app: ljwx-boot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ljwx-health-admin
  namespace: ljwx-health
  labels:
    app: ljwx-admin
    component: frontend
    helm.sh/chart: ljwx-health-0.1.0
    app.kubernetes.io/name: ljwx-health
    app.kubernetes.io/instance: ljwx-health
    app.kubernetes.io/version: 1.0.6
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ljwx-admin
  template:
    metadata:
      labels:
        app: ljwx-admin
        component: frontend
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: ljwx-admin
        image: harbor.eu.lingjingwanxiang.cn/ljwx-health/ljwx-admin:dev-latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ljwx-health-bigscreen
  namespace: ljwx-health
  labels:
    app: ljwx-bigscreen
    component: dashboard
    helm.sh/chart: ljwx-health-0.1.0
    app.kubernetes.io/name: ljwx-health
    app.kubernetes.io/instance: ljwx-health
    app.kubernetes.io/version: 1.0.6
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ljwx-bigscreen
  template:
    metadata:
      labels:
        app: ljwx-bigscreen
        component: dashboard
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: ljwx-bigscreen
        image: harbor.eu.lingjingwanxiang.cn/ljwx-health/ljwx-bigscreen:dev-latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5225
          protocol: TCP
        env:
        - name: ENV
          value: production
        - name: DB_HOST
          value: mysql-lb.infra.svc.cluster.local
        - name: DB_PORT
          value: '3306'
        - name: DB_NAME
          value: ljwx_health
        - name: REDIS_HOST
          value: redis-lb.infra.svc.cluster.local
        - name: REDIS_PORT
          value: '6379'
        - name: LOG_LEVEL
          value: INFO
        envFrom:
        - secretRef:
            name: ljwx-boot-secrets
        livenessProbe:
          httpGet:
            path: /health
            port: 5225
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5225
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ljwx-health-boot
  namespace: ljwx-health
  labels:
    app: ljwx-boot
    component: backend
    helm.sh/chart: ljwx-health-0.1.0
    app.kubernetes.io/name: ljwx-health
    app.kubernetes.io/instance: ljwx-health
    app.kubernetes.io/version: 1.0.6
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ljwx-boot
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9998'
        prometheus.io/path: /actuator/prometheus
      labels:
        app: ljwx-boot
        component: backend
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: ljwx-boot
        image: harbor.eu.lingjingwanxiang.cn/ljwx-health/ljwx-boot:dev-latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 9998
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql.infra.svc.cluster.local:3306/ljwx_health?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: com.mysql.cj.jdbc.Driver
        - name: SPRING_REDIS_HOST
          value: redis-lb.infra.svc.cluster.local
        - name: SPRING_REDIS_PORT
          value: '6379'
        - name: SPRING_REDIS_DATABASE
          value: '1'
        - name: SPRING_REDIS_PASSWORD
          value: '123456'
        - name: REDIS_HOST
          value: redis-lb.infra.svc.cluster.local
        - name: REDIS_PORT
          value: '6379'
        - name: REDIS_DB
          value: '1'
        - name: REDIS_PASSWORD
          value: '123456'
        - name: LOG_LEVEL
          value: INFO
        - name: SPRING_FLYWAY_ENABLED
          value: 'false'
        - name: SPRING_FLYWAY_BASELINE_ON_MIGRATE
          value: 'true'
        - name: SPRING_FLYWAY_LOCATIONS
          value: classpath:db/baseline
        - name: OTEL_SERVICE_NAME
          value: ljwx-boot
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://tempo.infra.svc.cluster.local:4317
        - name: OTEL_TRACES_SAMPLER
          value: parentbased_traceidratio
        - name: OTEL_TRACES_SAMPLER_ARG
          value: '0.1'
        - name: SPRING_PROFILES_INCLUDE
          value: device-approval
        envFrom:
        - secretRef:
            name: ljwx-boot-secrets
        - configMapRef:
            name: ljwx-health-device-approval-config
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/liveness
            port: 9998
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/readiness
            port: 9998
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: device-approval-config
          mountPath: /app/config/application-device-approval.yml
          subPath: application-device-approval.yml
          readOnly: true
      volumes:
      - name: logs
        emptyDir: {}
      - name: device-approval-config
        configMap:
          name: ljwx-health-device-approval-config
          items:
          - key: application-device-approval.yml
            path: application-device-approval.yml
      restartPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ljwx-health-api-ingress
  namespace: ljwx-health
  labels:
    helm.sh/chart: ljwx-health-0.1.0
    app.kubernetes.io/name: ljwx-health
    app.kubernetes.io/instance: ljwx-health
    app.kubernetes.io/version: 1.0.6
    app.kubernetes.io/managed-by: Helm
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: 'true'
    traefik.ingress.kubernetes.io/router.middlewares: ljwx-health-ljwx-health-strip-api-prefix@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - health-admin.lingjingwanxiang.cn
    secretName: ljwx-health-admin-tls
  rules:
  - host: health-admin.lingjingwanxiang.cn
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: ljwx-health-boot
            port:
              number: 9998
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ljwx-health-ingress
  namespace: ljwx-health
  labels:
    helm.sh/chart: ljwx-health-0.1.0
    app.kubernetes.io/name: ljwx-health
    app.kubernetes.io/instance: ljwx-health
    app.kubernetes.io/version: 1.0.6
    app.kubernetes.io/managed-by: Helm
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: 'true'
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - health-admin.lingjingwanxiang.cn
    secretName: ljwx-health-admin-tls
  - hosts:
    - health-dashboard.lingjingwanxiang.cn
    secretName: ljwx-health-bigscreen-tls
  rules:
  - host: health-admin.lingjingwanxiang.cn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ljwx-health-admin
            port:
              number: 80
  - host: health-dashboard.lingjingwanxiang.cn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ljwx-health-bigscreen
            port:
              number: 5225
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ljwx-health-strip-api-prefix
  namespace: ljwx-health
  labels:
    helm.sh/chart: ljwx-health-0.1.0
    app.kubernetes.io/name: ljwx-health
    app.kubernetes.io/instance: ljwx-health
    app.kubernetes.io/version: 1.0.6
    app.kubernetes.io/managed-by: Helm
spec:
  stripPrefix:
    prefixes:
    - /api
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ljwx-health-boot
  namespace: ljwx-health
  labels:
    app: ljwx-boot
    release: monitoring
    helm.sh/chart: ljwx-health-0.1.0
    app.kubernetes.io/name: ljwx-health
    app.kubernetes.io/instance: ljwx-health
    app.kubernetes.io/version: 1.0.6
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app: ljwx-boot
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
    scrapeTimeout: 10s
    relabelings:
    - sourceLabels:
      - __meta_kubernetes_service_name
      targetLabel: service
    - sourceLabels:
      - __meta_kubernetes_namespace
      targetLabel: namespace
    - sourceLabels:
      - __meta_kubernetes_pod_name
      targetLabel: pod
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ljwx-health-bigscreen
  namespace: ljwx-health
  labels:
    app: ljwx-bigscreen
    release: monitoring
    helm.sh/chart: ljwx-health-0.1.0
    app.kubernetes.io/name: ljwx-health
    app.kubernetes.io/instance: ljwx-health
    app.kubernetes.io/version: 1.0.6
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app: ljwx-bigscreen
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    relabelings:
    - sourceLabels:
      - __meta_kubernetes_service_name
      targetLabel: service
    - sourceLabels:
      - __meta_kubernetes_namespace
      targetLabel: namespace
    - sourceLabels:
      - __meta_kubernetes_pod_name
      targetLabel: pod
