apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-admin-ui.yaml
  - deployment-screen.yaml
  - deployment.yaml
  - ingress.yaml
  - servicemonitor.yaml
  - service-admin-ui.yaml
  - service-screen.yaml
  - service.yaml
