apiVersion: v1
kind: Service
metadata:
  name: ljwx-platform-screen
  labels:
    app: ljwx-platform-screen
    project: ljwx-platform
spec:
  selector:
    app: ljwx-platform-screen
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: ClusterIP
