apiVersion: v1
kind: Service
metadata:
  name: ljwx-platform-admin-ui
  labels:
    app: ljwx-platform-admin-ui
    project: ljwx-platform
spec:
  selector:
    app: ljwx-platform-admin-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: ClusterIP
