apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ljwx-platform
resources:
- ../../base
- runtime-config.yaml
images:
- name: ghcr.io/brunogao/ljwx-platform/ljwx-platform
  digest: sha256:1d168995293ae6eb4b0a6e467ca53d0a2ca9a8c4b46c232b1ae9268a846059a4
  newName: ghcr.io/brunogao/ljwx-platform/ljwx-platform
- name: ghcr.io/brunogao/ljwx-platform/ljwx-platform-admin-ui
  digest: sha256:a74f2a0111bf891d5d2259fa8d1671d88f70af0e2907b42dfc2a7717753521bb
- name: ghcr.io/brunogao/ljwx-platform/ljwx-platform-screen
  digest: sha256:e6329105f27ab04f2cec1b34f7d47984c953add37db63a398160eab8e86bf5a2
