apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ljwx-platform
resources:
- ../../base
images:
- name: harbor.omniverseai.net/app/ljwx-platform
  newName: harbor.eu.lingjingwanxiang.cn/ljwx/ljwx-platform
  newTag: c2740559342f7ccdf59c3fe84ca89f13dfe36c91
