apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ljwx-platform
resources:
- ../../base
- runtime-config.yaml
images:
- name: ghcr.io/brunogao/ljwx-platform/ljwx-platform
  digest: sha256:aeaa40c8d7478205993b77d04c858f43bdb71dca21ec36588ad87346101d602b
  newName: ghcr.io/brunogao/ljwx-platform/ljwx-platform
- name: ghcr.io/brunogao/ljwx-platform/ljwx-platform-admin-ui
  digest: sha256:30269d7678590b3790d79a180a5a21e0e51e7f4dda8f00fc379b0d670697fab9
- name: ghcr.io/brunogao/ljwx-platform/ljwx-platform-screen
  digest: sha256:e6329105f27ab04f2cec1b34f7d47984c953add37db63a398160eab8e86bf5a2
