apiVersion: v1
kind: Secret
metadata:
  name: ljwx-platform-db
  namespace: ljwx-platform
type: Opaque
stringData:
  DB_USERNAME: "<postgres_user>"
  DB_PASSWORD: "<postgres_password>"
  REDIS_PASSWORD: "<redis_password>"
  JWT_SECRET: "<jwt_secret_32_plus_chars>"
