apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ljwx-stock
resources:
- ../../base
- ingress.yaml
images:
- name: ghcr.io/brunogao/ljwx-stock/ljwx-stock-agent
  newName: ghcr.io/brunogao/ljwx-stock/ljwx-stock-agent
  digest: sha256:077c33f22a0d2950de2bf21ffd5b7729f51979b09647e097fd9510dd43a36531
