apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ljwx-stock
resources:
  - ../../base
images:
  - name: ghcr.io/brunogao/ljwx-stock/ljwx-stock-agent
    newName: ghcr.io/brunogao/ljwx-stock/ljwx-stock-agent
    newTag: bootstrap
