apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ljwx-core-api-dev
resources:
- ../../base
images:
- name: ghcr.io/brunogao/ljwx-core-api
  newName: ghcr.io/brunogao/ljwx-core-api
  digest: sha256:b7a9760defea2b10eabf468b20342ef6775185e147cc384b37fe7dc331b0c5cc
