apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ljwx-stock
resources:
- ../../base
images:
- name: ghcr.io/brunogao/ljwx-stock/ljwx-stock-qlib-predict
  newName: ghcr.io/brunogao/ljwx-stock/ljwx-stock-qlib-predict
  digest: sha256:9b310ac3e5f1079ac322b6ece4f532e43dc26fccfb9073bd8fce2fb697c0b606
- name: ghcr.io/brunogao/ljwx-stock/ljwx-stock-kline-etl
  newName: ghcr.io/brunogao/ljwx-stock/ljwx-stock-kline-etl
  digest: sha256:db529b61617eefd4b383e8f73668af1a272a883856c3e8cd32f5838ef5f03cc4
- name: ghcr.io/brunogao/ljwx-stock/ljwx-stock-qlib-bootstrap
  newName: ghcr.io/brunogao/ljwx-stock/ljwx-stock-qlib-bootstrap
  digest: sha256:6705bf8c0bb41bc36bbcdcfb021fb49c7b6bb3bb109f0ed37d8bf4118d755a51
