apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: infra
  labels:
    app: postgres
    component: database
    managed-by: gitops
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      component: database
  template:
    metadata:
      labels:
        app: postgres
        component: database
    spec:
      nodeSelector: {}
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-admin
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-admin
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          # Apply custom PostgreSQL configuration
          args:
            - "-c"
            - "max_connections=$(MAX_CONNECTIONS)"
            - "-c"
            - "shared_buffers=$(SHARED_BUFFERS)"
            - "-c"
            - "effective_cache_size=$(EFFECTIVE_CACHE_SIZE)"
            - "-c"
            - "maintenance_work_mem=$(MAINTENANCE_WORK_MEM)"
            - "-c"
            - "work_mem=$(WORK_MEM)"
            - "-c"
            - "wal_level=$(WAL_LEVEL)"
            - "-c"
            - "max_wal_size=$(MAX_WAL_SIZE)"
            - "-c"
            - "min_wal_size=$(MIN_WAL_SIZE)"
            - "-c"
            - "archive_mode=$(ARCHIVE_MODE)"
            - "-c"
            - "archive_command=$(ARCHIVE_COMMAND)"

          envFrom:
            - configMapRef:
                name: postgres-config

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-wal-archive
              mountPath: /var/lib/postgresql/wal_archive

          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2000m"

          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U $POSTGRES_USER
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U $POSTGRES_USER
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

  volumeClaimTemplates:
    - metadata:
        name: postgres-data
        labels:
          app: postgres
          component: database
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi

    - metadata:
        name: postgres-wal-archive
        labels:
          app: postgres
          component: database
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
