apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: youngth-guard-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BrunoGaoSZ/ljwx-deploy.git
    targetRevision: main
    path: apps/youngth-guard/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
