apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ljwx-bookstore
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: bookstore
    project: ljwx-bookstore
spec:
  project: ljwx
  source:
    repoURL: 'https://github.com/BrunoGaoSZ/ljwx-deploy.git'
    targetRevision: main
    path: apps/ljwx-bookstore/overlays/bookstore
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bookstore
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
