apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ljwx-core-api-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BrunoGaoSZ/ljwx-deploy.git
    targetRevision: main
    path: apps/ljwx-core-api/overlays/ljwx-core-api-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: ljwx-core-api-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
