apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-dev
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://community-charts.github.io/helm-charts
      chart: n8n
      targetRevision: 1.16.29
      helm:
        releaseName: n8n
        valueFiles:
          - $values/cluster/n8n-dev-values.yaml
    - repoURL: https://github.com/BrunoGaoSZ/ljwx-deploy.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
