apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-restore-TIMESTAMP  # Replace TIMESTAMP with actual time, e.g., postgres-restore-20251218143000
  namespace: infra
  labels:
    app: postgres
    component: restore
    managed-by: manual
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: postgres
        component: restore
    spec:
      restartPolicy: Never

      containers:
        - name: restore
          image: postgres:16-alpine
          command:
            - /bin/sh
            - -c
            - |
              set -e

              # ============================================
              # PostgreSQL Backup Restore
              # ============================================
              # IMPORTANT: This will OVERWRITE existing data!
              # Make sure you understand what you're doing!
              # ============================================

              BACKUP_DIR="/backup"
              RESTORE_FILE="${RESTORE_BACKUP_FILE}"

              echo "============================================"
              echo "PostgreSQL Restore Job"
              echo "============================================"
              echo "Start time: $(date)"
              echo "Restore file: ${RESTORE_FILE}"
              echo "============================================"

              # List available backups if no file specified
              if [ -z "${RESTORE_FILE}" ]; then
                echo "ERROR: RESTORE_BACKUP_FILE environment variable not set!"
                echo ""
                echo "Available backups:"
                ls -lh ${BACKUP_DIR}/*.sql.gz 2>/dev/null || echo "No backups found"
                echo ""
                echo "Usage:"
                echo "  Set RESTORE_BACKUP_FILE to one of the backup files above"
                echo "  Example: postgres_full_20251218_020000.sql.gz"
                echo "  Or: youngth_guard_dev_20251218_143000.sql.gz"
                exit 1
              fi

              BACKUP_PATH="${BACKUP_DIR}/${RESTORE_FILE}"

              # Check if backup file exists
              if [ ! -f "${BACKUP_PATH}" ]; then
                echo "ERROR: Backup file not found: ${BACKUP_PATH}"
                echo ""
                echo "Available backups:"
                ls -lh ${BACKUP_DIR}/*.sql.gz
                exit 1
              fi

              BACKUP_SIZE=$(du -h ${BACKUP_PATH} | cut -f1)
              echo "Backup file found: ${BACKUP_PATH}"
              echo "Backup size: ${BACKUP_SIZE}"

              # Determine restore type based on filename
              if echo "${RESTORE_FILE}" | grep -q "^postgres_full"; then
                RESTORE_TYPE="full"
                echo "Restore type: FULL (pg_dumpall - all databases)"
              else
                RESTORE_TYPE="single"
                DB_NAME=$(echo ${RESTORE_FILE} | sed 's/_[0-9]*\.sql\.gz$//')
                echo "Restore type: SINGLE DATABASE (${DB_NAME})"
              fi

              # Confirmation warning
              echo ""
              echo "⚠️  WARNING ⚠️"
              echo "This operation will:"
              if [ "${RESTORE_TYPE}" = "full" ]; then
                echo "  - DROP and RECREATE all databases"
                echo "  - OVERWRITE all data"
              else
                echo "  - DROP and RECREATE database: ${DB_NAME}"
                echo "  - OVERWRITE all data in ${DB_NAME}"
              fi
              echo ""
              echo "Proceeding in 5 seconds... (Press Ctrl+C to cancel)"
              sleep 5

              # Perform restore
              echo ""
              echo "============================================"
              echo "Starting restore..."
              echo "============================================"

              if [ "${RESTORE_TYPE}" = "full" ]; then
                # Full restore with pg_dumpall
                echo "Decompressing and restoring all databases..."
                gunzip -c ${BACKUP_PATH} | psql -h ${PGHOST} -U ${PGUSER} -d postgres

                echo ""
                echo "Verifying databases:"
                psql -h ${PGHOST} -U ${PGUSER} -d postgres -c "\l"

              else
                # Single database restore
                echo "Dropping existing database: ${DB_NAME}"
                psql -h ${PGHOST} -U ${PGUSER} -d postgres -c "DROP DATABASE IF EXISTS ${DB_NAME};"

                echo "Creating database: ${DB_NAME}"
                psql -h ${PGHOST} -U ${PGUSER} -d postgres -c "CREATE DATABASE ${DB_NAME};"

                echo "Restoring database from backup..."
                gunzip -c ${BACKUP_PATH} | psql -h ${PGHOST} -U ${PGUSER} -d ${DB_NAME}

                echo ""
                echo "Verifying tables:"
                psql -h ${PGHOST} -U ${PGUSER} -d ${DB_NAME} -c "\dt"
              fi

              echo ""
              echo "============================================"
              echo "✅ Restore completed successfully"
              echo "Completed at: $(date)"
              echo "============================================"
              echo ""
              echo "Next steps:"
              echo "1. Verify data integrity"
              echo "2. Test application connections"
              echo "3. Check application logs"

          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-admin
                  key: POSTGRES_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-admin
                  key: POSTGRES_PASSWORD
            - name: PGHOST
              value: postgres-lb.infra.svc.cluster.local
            - name: PGPORT
              value: "5432"
            # IMPORTANT: Set this to the backup file you want to restore
            # Examples:
            #   - postgres_full_20251218_020000.sql.gz (full backup)
            #   - youngth_guard_dev_20251218_143000.sql.gz (single database)
            - name: RESTORE_BACKUP_FILE
              value: ""  # MUST SET THIS VALUE!

          volumeMounts:
            - name: backup
              mountPath: /backup
              readOnly: true

          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2000m"

      volumes:
        - name: backup
          persistentVolumeClaim:
            claimName: pgbackrest-repo
