apiVersion: v1
kind: ConfigMap
metadata:
  name: ljwx-chat-config
data:
  NODE_ENV: "production"
  PORT: "3210"
  HOSTNAME: "0.0.0.0"

  DATABASE_DRIVER: "node"

  NEXT_PUBLIC_ENABLE_NEXT_AUTH: "0"
  NEXT_PUBLIC_ENABLE_LOCAL_AUTH: "1"
  NEXT_AUTH_SSO_SESSION_STRATEGY: "jwt"
  NEXT_AUTH_SSO_PROVIDERS: ""
  AUTH_TRUST_HOST: "true"
  DEFAULT_AGENT_CONFIG: 'model=lingjingwanxiang:32b;provider=ollama;systemRole="默认使用中文回答，除非用户明确要求使用其他语言。"'

  EMAIL_ENABLED: "false"

  NEXT_PUBLIC_BASE_URL: "https://chat.lingjingwanxiang.cn"
  NEXTAUTH_URL: "https://chat.lingjingwanxiang.cn"

  S3_BUCKET: "ljwx-chat"
  S3_ENABLE_PATH_STYLE: "1"

  MIDDLEWARE_REWRITE_THROUGH_LOCAL: "1"

  ENABLED_OLLAMA: "0"
  OPENCLAW_GATEWAY_URL: "https://openclaw.lingjingwanxiang.cn/v1"
  OPENCLAW_GATEWAY_ORIGIN: "https://openclaw.lingjingwanxiang.cn"
