---
# =============================================================================
# Database Initialization Job
# 在 infra namespace 的 MySQL 中创建 org_fiction 数据库
# =============================================================================
apiVersion: batch/v1
kind: Job
metadata:
  name: ljwx-bookstore-db-init
  namespace: ljwx-bookstore
  labels:
    app: ljwx-bookstore
    component: db-init
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: ljwx-bookstore
        component: db-init
    spec:
      restartPolicy: Never
      containers:
        - name: db-init
          image: mysql:8.0
          command:
            - /bin/bash
            - -c
            - |
              set -e
              echo "=== Starting Database Initialization ==="
              echo "Connecting to MySQL at ${DB_HOST}:${DB_PORT}..."

              # 等待 MySQL 就绪
              until mysql -h"${DB_HOST}" -P"${DB_PORT}" -u"${DB_USER}" -p"${DB_PASSWORD}" -e "SELECT 1" &>/dev/null; do
                echo "MySQL not ready, waiting 2 seconds..."
                sleep 2
              done

              echo "MySQL is ready! Creating database if not exists..."

              # 创建数据库
              mysql -h"${DB_HOST}" -P"${DB_PORT}" -u"${DB_USER}" -p"${DB_PASSWORD}" <<EOF
              CREATE DATABASE IF NOT EXISTS ${DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
              GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'%';
              FLUSH PRIVILEGES;
              SELECT 'Database ${DB_NAME} created or already exists' AS status;
              EOF

              echo "=== Database Initialization Completed Successfully ==="

          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: ljwx-bookstore-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: ljwx-bookstore-secret
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: ljwx-bookstore-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: ljwx-bookstore-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ljwx-bookstore-secret
                  key: DB_PASSWORD

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
