---
# =============================================================================
# ljwx-bookstore Secret Configuration
# 包含数据库凭据和其他敏感信息
# 注意：实际部署时需要替换为真实的值（base64编码）
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: ljwx-bookstore-secret
  namespace: ljwx-bookstore
  labels:
    app: ljwx-bookstore
    component: config
type: Opaque
stringData:
  # 数据库配置 - 使用 infra namespace 的 MySQL
  # 注意：在实际部署时，请替换为真实的密码
  DB_HOST: "mysql-infra.infra.svc.cluster.local"
  DB_PORT: "3306"
  DB_NAME: "org_fiction"
  DB_USER: "root"
  DB_PASSWORD: "123456"  # 从 infra namespace 的 MySQL secret 获取

  # Redis配置 - 使用 infra namespace 的 Redis
  REDIS_HOST: "redis-infra-master.infra.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "123456"  # 从 infra namespace 的 Redis secret 获取

  # 微信支付配置
  WX_APP_SECRET: "REPLACE_WITH_WX_APP_SECRET"
  WX_MCH_KEY: "REPLACE_WITH_WX_MCH_KEY"

  # 邮件配置
  MAIL_PASSWORD: "REPLACE_WITH_MAIL_PASSWORD"

  # 短信配置
  SMS_TENCENT_APPKEY: "REPLACE_WITH_SMS_APPKEY"
  SMS_ALIYUN_ACCESS_KEY_SECRET: "xxx"

  # 对象存储配置
  STORAGE_ALIYUN_ACCESS_KEY_ID: "REPLACE_WITH_ALIYUN_ACCESS_KEY_ID"
  STORAGE_ALIYUN_ACCESS_KEY_SECRET: "REPLACE_WITH_ALIYUN_ACCESS_KEY_SECRET"
  STORAGE_TENCENT_SECRET_ID: "REPLACE_WITH_TENCENT_SECRET_ID"
  STORAGE_TENCENT_SECRET_KEY: "REPLACE_WITH_TENCENT_SECRET_KEY"

  # AI配置（可选）
  AI_CLOUD_API_KEY: ""  # 如果使用云端AI服务
---
# =============================================================================
# 说明：获取 infra namespace 密码的命令
# =============================================================================
# # 获取 MySQL root 密码：
# kubectl get secret -n infra mysql-backup-credentials -o jsonpath='{.data.password}' | base64 -d
#
# # 获取 Redis 密码：
# kubectl get secret -n infra redis-infra -o jsonpath='{.data.redis-password}' | base64 -d
#
# # 使用真实密码更新 Secret：
# kubectl create secret generic ljwx-bookstore-secret \
#   --from-literal=DB_PASSWORD='actual-mysql-password' \
#   --from-literal=REDIS_PASSWORD='actual-redis-password' \
#   --namespace=ljwx-bookstore \
#   --dry-run=client -o yaml | kubectl apply -f -
# =============================================================================
