apiVersion: v1
kind: Secret
metadata:
  name: deploy-promoter-secret
  namespace: dev
type: Opaque
stringData:
  github_token: "<github_token_with_repo_workflow>"
  harbor_url: "https://harbor.example.com"
  harbor_username: "<harbor_user>"
  harbor_password: "<harbor_password>"
  argocd_server: "https://argocd.example.com"
  argocd_token: "<argocd_token>"
