resources:
  - namespace-dev.yaml
  - namespace-ljwx-website-dev.yaml
  - namespace-ljwx-bookstore.yaml
  - website-dev-application.yaml
  - ljwx-platform-observability-application.yaml
  - deploy-promoter-cronjob.yaml
  - smoke-runner-cronjob.yaml
  - regcred.yaml
  - default-sa.yaml
  - stock-etl-qlib-predict-application.yaml
