apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stock-agent-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BrunoGaoSZ/ljwx-deploy.git
    targetRevision: main
    path: apps/stock-agent/overlays/ljwx-stock
  destination:
    server: https://kubernetes.default.svc
    namespace: ljwx-stock
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
