services:
  backend:
    envs:
      dev:
        overlayPath: apps/backend/overlays/dev/kustomization.yaml
        kustomizeImageName: harbor.omniverseai.net/ljwx/backend-template
        harborImage: harbor.omniverseai.net/app/backend
        argocdApp: backend-dev
  frontend:
    envs:
      dev:
        overlayPath: apps/frontend/overlays/dev/kustomization.yaml
        kustomizeImageName: harbor.omniverseai.net/ljwx/frontend-dashboard
        harborImage: harbor.omniverseai.net/app/frontend
        argocdApp: frontend-dev
  quality-dashboard:
    envs:
      dev:
        overlayPath: apps/quality-dashboard/overlays/dev/kustomization.yaml
        kustomizeImageName: harbor.omniverseai.net/ljwx/quality-dashboard
        harborImage: harbor.omniverseai.net/app/quality-dashboard
        argocdApp: quality-dashboard-dev
  ljwx-website:
    envs:
      dev:
        overlayPath: apps/ljwx-website/overlays/ljwx-website-dev/kustomization.yaml
        kustomizeImageName: ghcr.io/brunogao/ljwx-website
        harborImage: harbor.eu.lingjingwanxiang.cn/app/ljwx-website
        argocdApp: ljwx-website-dev
      prod:
        overlayPath: apps/ljwx-website/overlays/ljwx-website-prod/kustomization.yaml
        kustomizeImageName: ghcr.io/brunogao/ljwx-website
        harborImage: harbor.omniverseai.net/ljwx/ljwx-website
        deployImage: harbor.omniverseai.net/ljwx/ljwx-website
        argocdApp: ljwx-website-prod
  ljwx-bookstore:
    envs:
      dev:
        overlayPath: apps/ljwx-bookstore/overlays/ljwx-bookstore/kustomization.yaml
        kustomizeImageName: harbor.omniverseai.net/ljwx/ljwx-bookstore
        harborImage: harbor.omniverseai.net/app/ljwx-bookstore
        argocdApp: ljwx-bookstore
  ljwx-health-boot:
    envs:
      dev:
        overlayPath: apps/ljwx-health/overlays/ljwx-boot/kustomization.yaml
        kustomizeImageName: harbor.omniverseai.net/ljwx-health/ljwx-boot
        harborImage: harbor.omniverseai.net/app/ljwx-health-boot
        argocdApp: ljwx-health-boot
  ljwx-health-admin:
    envs:
      dev:
        overlayPath: apps/ljwx-health/overlays/ljwx-admin/kustomization.yaml
        kustomizeImageName: harbor.omniverseai.net/ljwx-health/ljwx-admin
        harborImage: harbor.omniverseai.net/app/ljwx-health-admin
        argocdApp: ljwx-health-admin
  ljwx-health-bigscreen:
    envs:
      dev:
        overlayPath: apps/ljwx-health/overlays/ljwx-bigscreen/kustomization.yaml
        kustomizeImageName: harbor.omniverseai.net/ljwx-health/ljwx-bigscreen
        harborImage: harbor.omniverseai.net/app/ljwx-health-bigscreen
        argocdApp: ljwx-health-bigscreen
  ljwx-platform:
    envs:
      prod:
        overlayPath: apps/ljwx-platform/overlays/prod/kustomization.yaml
        kustomizeImageName: harbor.omniverseai.net/app/ljwx-platform
        harborImage: harbor.omniverseai.net/app/ljwx-platform
        argocdApp: ljwx-platform
  ljwx-stock-qlib-predict:
    envs:
      dev:
        overlayPath: apps/stock-etl/overlays/ljwx-stock/kustomization.yaml
        kustomizeImageName: ghcr.io/brunogao/ljwx-stock/ljwx-stock-qlib-predict
        harborImage: harbor.eu.lingjingwanxiang.cn/ljwx/ljwx-stock-qlib-predict
        argocdApp: stock-etl-qlib-predict-dev
  ljwx-stock-kline-etl:
    envs:
      dev:
        overlayPath: apps/stock-etl/overlays/ljwx-stock/kustomization.yaml
        kustomizeImageName: ghcr.io/brunogao/ljwx-stock/ljwx-stock-kline-etl
        harborImage: harbor.eu.lingjingwanxiang.cn/ljwx/ljwx-stock-kline-etl
        argocdApp: stock-etl-qlib-predict-dev
  ljwx-stock-qlib-bootstrap:
    envs:
      dev:
        overlayPath: apps/stock-etl/overlays/ljwx-stock/kustomization.yaml
        kustomizeImageName: ghcr.io/brunogao/ljwx-stock/ljwx-stock-qlib-bootstrap
        harborImage: harbor.eu.lingjingwanxiang.cn/ljwx/ljwx-stock-qlib-bootstrap
        argocdApp: stock-etl-qlib-predict-dev
  ljwx-stock-agent:
    envs:
      dev:
        overlayPath: apps/stock-agent/overlays/ljwx-stock/kustomization.yaml
        kustomizeImageName: ghcr.io/brunogao/ljwx-stock/ljwx-stock-agent
        harborImage: harbor.eu.lingjingwanxiang.cn/ljwx/ljwx-stock-agent
        argocdApp: stock-agent-dev
  ljwx-dify:
    envs:
      dev:
        overlayPath: apps/ljwx-dify/overlays/ljwx-dify-dev/kustomization.yaml
        kustomizeImageName: ghcr.io/brunogao/ljwx-dify-api
        harborImage: harbor.eu.lingjingwanxiang.cn/app/ljwx-dify-api
        argocdApp: ljwx-dify-dev
  ljwx-dify-web:
    envs:
      dev:
        overlayPath: apps/ljwx-dify/overlays/ljwx-dify-dev/kustomization.yaml
        kustomizeImageName: ghcr.io/brunogao/ljwx-dify-web
        harborImage: harbor.eu.lingjingwanxiang.cn/app/ljwx-dify-web
        argocdApp: ljwx-dify-dev
  ljwx-chat:
    envs:
      dev:
        overlayPath: apps/ljwx-chat/overlays/ljwx-chat-dev/kustomization.yaml
        kustomizeImageName: ghcr.io/brunogao/ljwx-chat
        harborImage: harbor.eu.lingjingwanxiang.cn/app/ljwx-chat
        argocdApp: ljwx-chat-dev
