apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  annotations:
    # ============================================
    # ArgoCD PreSync Hook
    # ============================================
    # 这个 Job 会在应用部署前执行
    # 如果失败，会阻止应用部署
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app: youngth-guard-backend
    component: migration
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        component: migration
    spec:
      restartPolicy: Never

      # ============================================
      # Init Container: 等待数据库就绪
      # ============================================
      initContainers:
        - name: wait-for-db
          image: postgres:16-alpine
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for database to be ready..."
              until pg_isready -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER; do
                echo "Database is unavailable - sleeping"
                sleep 2
              done
              echo "Database is ready!"
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-youngth-guard-dev
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-youngth-guard-dev
                  key: POSTGRES_PORT
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-youngth-guard-dev
                  key: POSTGRES_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-youngth-guard-dev
                  key: POSTGRES_PASSWORD

      # ============================================
      # Main Container: Flyway Migration
      # ============================================
      containers:
        - name: flyway
          image: flyway/flyway:10-alpine
          command:
            - /bin/sh
            - -c
            - |
              set -e

              echo "============================================"
              echo "Database Migration with Flyway"
              echo "============================================"
              echo "Database: $FLYWAY_URL"
              echo "User: $FLYWAY_USER"
              echo "Migrations: /flyway/sql"
              echo "============================================"

              # 列出迁移文件
              echo "Available migrations:"
              ls -la /flyway/sql/ || echo "No migrations found"

              # 执行迁移
              echo ""
              echo "Running migrations..."
              flyway -connectRetries=3 migrate

              # 显示迁移历史
              echo ""
              echo "Migration history:"
              flyway info

              echo ""
              echo "✅ Migration completed successfully"

          env:
            # Flyway 配置
            - name: FLYWAY_URL
              value: "jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-youngth-guard-dev
                  key: POSTGRES_USER
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-youngth-guard-dev
                  key: POSTGRES_PASSWORD

            # 从 Secret 获取连接信息
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-youngth-guard-dev
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-youngth-guard-dev
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-youngth-guard-dev
                  key: POSTGRES_DB

            # Flyway 选项
            - name: FLYWAY_BASELINE_ON_MIGRATE
              value: "true"
            - name: FLYWAY_BASELINE_VERSION
              value: "0"
            - name: FLYWAY_OUT_OF_ORDER
              value: "false"
            - name: FLYWAY_VALIDATE_ON_MIGRATE
              value: "true"

          volumeMounts:
            - name: migrations
              mountPath: /flyway/sql
              readOnly: true

          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"

      # ============================================
      # Volumes: 挂载迁移文件
      # ============================================
      volumes:
        - name: migrations
          configMap:
            name: db-migrations
