apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cronjob-qlib-predict-to-pg.yaml
  - pvc-qlib.yaml

commonLabels:
  app.kubernetes.io/name: stock-etl-qlib-predict
  app.kubernetes.io/part-of: ljwx-stock
