apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap-kline-etl.yaml
  - cronjob-kline-backfill-1200.yaml
  - cronjob-kline-daily-refresh.yaml
  - cronjob-kline-quarterly-reconcile.yaml
  - cronjob-qlib-predict-to-pg.yaml
  - pvc-qlib.yaml

commonLabels:
  app.kubernetes.io/part-of: ljwx-stock
