apiVersion: apps/v1
kind: Deployment
metadata:
  name: ljwx-website
spec:
  template:
    spec:
      containers:
        - name: ljwx-website
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
