apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ljwx-website-dev
resources:
- ../../base
patches:
- path: service-nodeport.yaml
- path: deployment-probe.yaml
images:
- name: ghcr.io/brunogao/ljwx-website
  newName: ghcr.io/brunogao/ljwx-website
  digest: sha256:be26e0c85044cc520a12ff0be4b469a216e4e1b55106175f1156a749c1097ac4
replicas:
- name: ljwx-website
  count: 1
