apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ljwx-website-dev
resources:
- ../../base
- ingress.yaml
patches:
- path: service-nodeport.yaml
- path: deployment-probe.yaml
images:
- name: ghcr.io/brunogao/ljwx-website
  newName: harbor.eu.lingjingwanxiang.cn/ljwx/ljwx-website
  digest: sha256:c4f4a59ca033b0c383590424477c2b6402597aaec68a45ba38ef67b1c784e6c9
replicas:
- name: ljwx-website
  count: 1
