apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ljwx-bookstore
resources:
- ../../base
images:
- name: harbor.omniverseai.net/ljwx/ljwx-bookstore
  newName: ghcr.io/brunogaosz/ljwx-bookstore
  digest: sha256:21072d47881b2bd303fb3dc104d6704a71974790396d2ad9d433ed46bdc2bc24
replicas:
- name: ljwx-bookstore
  count: 1
