apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ljwx-bookstore
resources:
- ../../base
images:
- name: harbor.omniverseai.net/ljwx/ljwx-bookstore
  newName: ghcr.io/brunogaosz/ljwx-bookstore
  digest: sha256:9a5046ac7c7303949a8630919d4bd280c40362b00820a7ae0c98467ab36ec599
replicas:
- name: ljwx-bookstore
  count: 1
