apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ljwx-bookstore
resources:
- ../../base
images:
- name: harbor.omniverseai.net/ljwx/ljwx-bookstore
  newName: ghcr.io/brunogaosz/ljwx-bookstore
  digest: sha256:7b688c4e973c602859c91aecccdece5d9c3dd1348dea32080b4b1d39481aee0d
replicas:
- name: ljwx-bookstore
  count: 1
