apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: infra
  labels:
    app: redis
    component: cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path

